apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlServerVolumeClaim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  storageClassName: netapppv
