apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv
spec:
  mountOptions:
    - hard
    - nfsvers=3
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nostalgic-admiring-almeida
    server: "10.33.19.4"
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 100Gi
  storageClassName: netapppv
  volumeMode: Filesystem