apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netappclaim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  storageClassName: netapppv